version: '3.8' 

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "5002:5002"  
    depends_on:
      - redis  

  redis:
    image: redis:latest  
    ports:
      - "6379:6379"  
